#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pharmacy
#    username: root
#    password: 12345
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 9090
#
#
#  image:
#    upload:
#      dir: "pharmacy-service/src/main/resources/static/images"
#
#  spring:
#    servlet:
#      multipart:
#        enabled: true
#        file-size-threshold: 2KB
#        max-file-size: 10MB
#        max-request-size: 10MB
#
#
#
#
